name: Build Ostree Container Image

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '00 0 1 * *'
  push:
    branches: [ '*' ]


jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fedora:latest
      options: --privileged
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build
        env:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
          image: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          composefile: container.yaml
        run: |
          set -eux
          dnf -y install rpm-ostree skopeo selinux-policy-targeted podman buildah /usr/bin/fuse-overlayfs
          sed -i 's/#mount_program/mount_program/' /etc/containers/storage.conf
          skopeo login -u $username -p $password $registry
          mkdir -p repo cache
          ostree init --repo=repo --mode=archive
          rpm-ostree compose tree --unified-core \
            --repo=repo --cachedir=cache \
            $composefile
          rpm-ostree compose container-encapsulate \
            --repo=repo --cmd /bin/bash --max-layers 8 \
            container containers-storage:build_tmp
          podman push --force-compression --compression-format zstd:chunked \
            containers-storage:build_tmp $registry/$image:$tag

            
